# Site settings 配置站点
title: 'Sphinx'
description: 'Welcome to the riddle cave'
keywords: 'blog, Sphinx'
url: 'https://FarCaptain.github.io' 
# your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  Home: '/'
  Tags: '/tags.html'
  Timeline: '/timeline.html'
  About Me: '/about.html'
  #友情链接: '/friendLink.html'
  Code Samples: 'https://lucaschyu.myportfolio.com/'

# 博主
author: true
name: 'Lucas Qu'
NickName: '(loo-kus ch-yuu)'
webtitle: 'Sphinx’s Riddle Cave'
bio: 'Game Programmer/Engineer focusing on <b>gameplay</b> and <b>tools</b> programming'
about: true
aboutyou: 'Lucas is a skilled Game Engineering professional with experience in game programming and engine-level code; loves solving complex problems and has a thirst for learning new stuff; very fast at prototyping features, but understands enough about software architecture to scale to production-level code.
<br />
<br />
<br />
  Check out my Resume <a href="https://lucaschyu.myportfolio.com/my-resume/">Here</a>
<br />
<br />
<br /><br />

  Some of my favourate games are: <br />
  &#x2022; Hades - Satisfying and fun roguelite gameplay with an awesome narrative.<br />
  &#x2022; Journey - An emotional roller coaster.<br />
  &#x2022; Gris - A story about losing with stunning art.<br />
'
portraits: '/assets/me.png' 
#your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:quyuan2008@163.com'
  #weixin: '' # 你的微信二维码存放的地址
  #qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/FarCaptain'
  #Codepen: ''
  weibo: 'https://weibo.com/u/5730149167'
  #instagram: ''
  #Twitter: ''
  #Dribbble: ''
  #Facebook: ''
  #Google: ''
  #zhihu: ''
  #juejin: ''
  #twitch: ''

# 分页
paginate: 4
paginatepath: ['page:num']

# since
footer:
  since: 2020

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'tango'

# 友情链接
friends:
  #jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: false
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
